### ISSUE TITLE
identify duplicated types in casper-test and move to casper-types

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/roadmap#155]

**Comment by Fraser999** [comment]
Closing as won't do, since there are very few duplicated types (only [these four](https://github.com/casper-network/casper-test/blob/e8bb54bfa3892ce809122e9e80e74ea5668fb56a/src/environment.rs#L112-L156) afaik), and these types are simple.

This origins of this ticket probably predate many node types being made available via the client, and which `casper-test` now uses rather than duplicating them here too.
