### ISSUE TITLE
add a test using the disk_use tool to prove the delta in disk usage running the auction (run the test before and after)

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/roadmap#196]

**Comment by devendran-m** [comment]
Triaged and closed.

**Comment by devendran-m** [comment]
Won't do

**Comment by devendran-m** [comment]
The following is a summary of the rationale shared by Ed during the triage on 27th Sep '24. The summary is created based on the points he shared on the call for future reference and audit trial.

### Summary:

The suggestion to use a disk usage tool to measure data size changes during the auction process is deemed unnecessary. Since the data structures involved are of fixed width, it's possible to accurately calculate the additional storage without benchmarking tools.

### Detailed Rationale:

**Fixed-Width Structures:** The data structures for storing delegator information are of fixed size, meaning their byte sizes are constant and known in advance.

**Calculation of Additional Storage:**

When unpacking delegators embedded within a validator's bid, the delegator key information is separated and a new key is created.
This process adds:

- 1 byte for the key tag.
- 33 bytes for the composite key, which includes the delegator's key, the public key, and the validator's public key.
- 1 byte extra for the stored value.
- Total Additional Bytes per Entry: 34 bytes.- 

**Total Storage Calculation:** Multiply the number of delegators by 34 bytes to get the total additional storage required.

**Unnecessary Benchmarking:** Since the sizes are fixed and precisely known, using a tool to measure disk usage would simply confirm what can already be calculated mathematically. This makes the use of such a tool redundant.

**LMDB Paging Considerations:**

- While it's true that the underlying database (LMDB) may have internal storage overhead due to paging, this overhead affects all data uniformly.
- If paging overhead were a concern, it would necessitate measuring disk usage for all data stored, not just the delegator entries.
- Therefore, focusing on this specific case without addressing the entire data set lacks practical justification. 

**Conclusion:**

Given that the additional storage can be accurately determined through straightforward calculations and that any database-specific overhead applies universally, employing a disk usage tool for this purpose is unnecessary.
